services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rocklms
      POSTGRES_USER: rocklms-user
      POSTGRES_PASSWORD: rocklms-pass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: